Data sim
zaccharieramzi/phylo-hmm pull request #3
Opened 2016-12-28 14:22 UTC by dEcmir

OK donc le voilà le main est un script pour l'exemple jouet
Pour le tester:
`python data_simulation tree.json -n <ton entier favori>`

2016-12-28 17:22 UTC, zaccharieramzi requested changes
Je crois qu'on n'est pas au clair sur la fonction `generat_initial_vector`. Appelle moi quand tu peux qu'on en discute.

2016-12-28 17:22 UTC, zaccharieramzi commented on tree_serialisation.py
> +        f.close()
Quand t'as un `with`, tu n'as pas besoin de fermer le fichier ou même de flush.

2016-12-28 17:22 UTC, zaccharieramzi commented on tree_serialisation.py
> +            json.dumps(tree, sort_keys=True, indent=4, separators=(',', ': ')))
Tu n'as pas besoin de le transformer en string puis de l'écrire dans le fichier. `json` a une méthode pour sauvegarder directement dans un fichier : https://docs.python.org/3/library/json.html#basic-usage

2016-12-28 17:22 UTC, zaccharieramzi commented on tree_serialisation.py
> +        tree = json.loads(f.read())
pareil ici tu peux directement utiliser ça : https://docs.python.org/3/library/json.html#json.load

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +    A[3, 3] = 0.9999  # unrealistic ...
Pourquoi tu mets unrealistic ? c'est ce qui est dans le papier donc je pense qu'il faut utiliser ça.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +    kappa = np.array([2.3, 2.7, 4.3, 5.4])
Pour moi tout ça (les paramètres), faudrait le mettre dans une fonction (ou pas d'ailleurs, réfléchir à un fichier de config) à part qui renvoie un dico avec tous les paramètres. Ça permettra de les réutiliser plus facilement.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +            Q[j, i, i] -= np.sum(Q[j, i, :])
J'ai le sentiment qu'il faut faire ça aussi mais tu as trouvé une confirmation qq part ?

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +def generate_initial_vector(b, nbNucleotids):
Je comprends pas du tout cette fonction

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +    states[0] = np.random.randint(0, nbState, 1)[0]
Ok je pense qu'on n'est pas d'accord sur le modèle. Pour moi c'est là que tu dois utiliser `b`. J'ai pas compris la fonction d'avant. Mais `b` sert juste à initialiser tes états. Du coup ici faut pas tirer sur la loi uniforme sur les états mais sur la loi définie par `b`.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +        discrete_law = A[states[i]]
c'est pas `states[i-1]` ?

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +            - nbState (np matrix) state transition matrix
il y a un petit problème de doc ici.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +        discrete_law = A[states[i]]
voire `A[states[i-1], :]` ?

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +            - X (np vector):  nucleotids as integers
Ok je comprends maintenant ce que tu fais avec `generate_initial_vector`. Mais il ne faut pas utiliser `b` qui est un vecteur de probabilité correspondant aux états mais bien `pi` qui correspond lui aux nucléotides.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +            - tree with same shape but randomised branches length
Je pense qu'il y a une erreur dans la doc là.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +    def evolve(node, vector):
le nom de la variable `vector` est pas claire du coup ça ralentit ma compréhension de la fonction.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +                for j in range(len(Q)):
pour moi c'est pas clair de mettre `len(Q)`, ici, il vaudrait mieux mettre `len(trees)`, mais c'est sujet à interprétation. Je trouve que c'est plus parlant avec les arbres.

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +            return res
Du coup ton résultat au final c'est une liste de liste c'est ça ?

2016-12-28 17:22 UTC, zaccharieramzi commented on data_simulation.py
> +    strands = evolution(X, states, trees, Q)
Du coup après avoir compris la fonction `evolution`, ici en fait il ne faut mettre que les `strands` de 1 à 8 non ?
Parce que celles des états intermédiaires en fait on n'y a pas accès .

2016-12-28 17:24 UTC, dEcmir commented on data_simulation.py
> +            return res
yes

2016-12-28 17:26 UTC, dEcmir commented on data_simulation.py
> +    def evolve(node, vector):
oui c'est vrai

2016-12-28 17:27 UTC, dEcmir commented on data_simulation.py
> +            - tree with same shape but randomised branches length
yes !

2016-12-28 17:31 UTC, dEcmir commented on data_simulation.py
> +        discrete_law = A[states[i]]
en python ces deux choses sont équivalentes. 
à chaque itération je cherche à déterminer l'état suivant *i+1*

2016-12-28 17:33 UTC, zaccharieramzi commented on data_simulation.py
> +        discrete_law = A[states[i]]
Ouais bien sûr my bad, mauvaise manipulation des indices. Cela dit le coup des deux points ne reste pas vrai ?

2016-12-28 17:34 UTC, dEcmir commented on data_simulation.py
> +            Q[j, i, i] -= np.sum(Q[j, i, :])
ça ? oui ils mentionnent HKY dans le papier

2016-12-28 17:34 UTC, dEcmir commented on data_simulation.py
> +            - nbState (np matrix) state transition matrix
yes

2016-12-28 17:35 UTC, dEcmir commented on data_simulation.py
> +            - X (np vector):  nucleotids as integers
ah ouais cela me parait sensé
du coup tirer l'état initial au hasard est une erreur non ?

2016-12-28 17:37 UTC, zaccharieramzi commented on data_simulation.py
> +            Q[j, i, i] -= np.sum(Q[j, i, :])
sommer à zéro.

2016-12-28 17:37 UTC, dEcmir commented on data_simulation.py
> +        discrete_law = A[states[i]]
en terme de fonctionnement non. Mais après stylistiquement ça fait pe prendre conscience de la dimension de A...

2016-12-28 17:37 UTC, zaccharieramzi commented on data_simulation.py
> +            - X (np vector):  nucleotids as integers
on peut s'appeler pour ce coup là !

2016-12-28 17:38 UTC, zaccharieramzi commented on data_simulation.py
> +        discrete_law = A[states[i]]
d'ac ok j'avais jamais fait gaffe. 
Du coup ouais ptet plus clair avec les deux points mais pas critique du coup

2016-12-28 17:42 UTC, dEcmir commented on data_simulation.py
> +    strands = evolution(X, states, trees, Q)
d'après ma compréhension de ce qu'il faut faire (et c'est le point important), j'utilise successivement les matrices de transition `B = exp(At)` et je les applique
 sur les noeuds cachés en parcourant l'arbre jusqu'à avoir 8 `strands`

2016-12-28 18:31 UTC, dEcmir commented on data_simulation.py
> +    A[3, 3] = 0.9999  # unrealistic ...
justement dans le papier ils indiquent utiliser une valeur plus basse parce que sinon il n'y aurait qu'un gène et encore sur 10000 sites ...

2016-12-30 12:39 UTC, dEcmir commented on data_simulation.py
> +    A[3, 3] = 0.9999  # unrealistic ...
je croyais t'avoir répondu, en gros ça impliquerai de générer des données énormes pour avoir quelques gènes en pratique le papier utilise une valeur plus petite, ce que j'ai indiqué par ce commentaire

2016-12-30 12:42 UTC, dEcmir commented on data_simulation.py
> +                for j in range(len(Q)):
j'en ai tenu compte dans une version ultérieure

2016-12-30 12:56 UTC, zaccharieramzi approved these changes

2016-12-30 12:58 UTC, zaccharieramzi commented on tree_serialisation.py
> +    json.dump(tree, file_path, sort_keys=True, indent=4,
je suis pas sûr que ça marche ça ... Il faut quand même ouvrir le fichier pour le dump.

2016-12-30 12:58 UTC, zaccharieramzi commented on tree_serialisation.py
> +    tree = json.load(filePath)
pareil ici non ?

2016-12-30 13:02 UTC, dEcmir commented on tree_serialisation.py
> +    json.dump(tree, file_path, sort_keys=True, indent=4,
ah oui exact ...
 du coup le changement n'a pas trop d'intéret

2016-12-30 13:04 UTC, zaccharieramzi commented on tree_serialisation.py
> +    json.dump(tree, file_path, sort_keys=True, indent=4,
si si bien sur mais il faut juste pas faire tous les trucs genre close, etc et print

2016-12-30 13:08 UTC, merged